OPTIONS (DIRECT=TRUE, ERRORS=1, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '/opt/oracle/MHOLIDAY_DATA.csv'
INTO TABLE MHOLIDAY
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MHOLIDAYPK  INTEGER EXTERNAL,
    HOLIDAY     DATE "YYYY-MM-DD",
    DESCRIPTION CHAR,
    LASTUPDATED TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
    UPDATEDBY   CHAR
)
