OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=10, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '/opt/oracle/MICON_DATA.csv'
INTO TABLE MICON
APPEND
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '"'

(
    MICONPK  INTEGER EXTERNAL NULLIF MICONPK = 'NULL',
    ICONNAME CHAR NULLIF ICONNAME = 'NULL',
    ICONPATH CHAR NULLIF ICONPATH = 'NULL',
    URL      CHAR NULLIF URL = 'NULL'
)