OPTIONS (DIRECT=TRUE, ERRORS=0, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE 'MICON_DATA.csv'
INTO TABLE MICON
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MICONPK  INTEGER EXTERNAL,
    ICONNAME CHAR,
    ICONPATH CHAR,
    URL      CHAR
)