OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '/opt/oracle/MLETTER_DATA.csv'
INTO TABLE MLETTER
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MLETTERPK    INTEGER EXTERNAL,
    LETTERPREFIX CHAR,
    DESCRIPTION  CHAR,
    LASTUPDATED  TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
    UPDATEDBY    CHAR,
    PRODUCTGROUP CHAR
)