OPTIONS (DIRECT=TRUE, ERRORS=0, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE 'MLETTERTYPE_DATA.csv'
INTO TABLE MLETTERTYPE
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MLETTERTYPEPK INTEGER EXTERNAL,
    PRODUCTGROUP  CHAR,
    LETTERTYPE    CHAR,
    DESCRIPTION   CHAR,
    LASTUPDATED   TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
    UPDATEDBY     CHAR
)