OPTIONS (DIRECT=TRUE, ERRORS=0, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE 'MNOTIF_DATA.csv'
INTO TABLE MNOTIF
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$'
TRAILING NULLCOLS

(
    NOTIFID       CHAR(10),
    NOTIFNAME     CHAR(100),
    NOTIFTYPE     CHAR(1),
    NOTIFPAGEPATH CHAR(100)
)
