OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=10, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '/opt/oracle/MPRODUCTGROUP_DATA.csv'
INTO TABLE MPRODUCTGROUP
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '"'

(
    MPRODUCTGROUPPK  INTEGER EXTERNAL NULLIF MPRODUCTGROUPPK = 'NULL',
    PRODUCTGROUPCODE CHAR NULLIF PRODUCTGROUPCODE = 'NULL',
    PRODUCTGROUP     CHAR NULLIF PRODUCTGROUP = 'NULL',
    ISCOA            CHAR NULLIF ISCOA = 'NULL'
)
