OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '/opt/oracle/MPRODUCTGROUP_DATA.csv'
INTO TABLE MPRODUCTGROUP
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MPRODUCTGROUPPK  INTEGER EXTERNAL,
    PRODUCTGROUPCODE CHAR,
    PRODUCTGROUP     CHAR,
    ISCOA            CHAR
)
