OPTIONS (DIRECT=TRUE, ERRORS=0, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE 'MPRODUCTGROUP_DATA.csv'
INTO TABLE MPRODUCTGROUP
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MPRODUCTGROUPPK  INTEGER EXTERNAL,
    PRODUCTGROUPCODE CHAR,
    PRODUCTGROUP     CHAR,
    ISCOA            CHAR
)
