OPTIONS (DIRECT=TRUE, ERRORS=0, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE 'MPRODUCTOWNER_DATA.csv'
INTO TABLE MPRODUCTOWNER
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$'
TRAILING NULLCOLS

(
    MPRODUCTOWNERPK INTEGER EXTERNAL,
    MBRANCHFK       INTEGER EXTERNAL
)