OPTIONS (DIRECT=TRUE, ERRORS=1, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '/opt/oracle/MREGION_DATA.csv'
INTO TABLE MREGION
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MREGIONPK   INTEGER EXTERNAL,
    REGIONID    CHAR,
    REGIONCODE  CHAR,
    REGIONNAME  CHAR,
    LASTUPDATED TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF6",
    UPDATEDBY   CHAR
)
