OPTIONS (DIRECT=TRUE, ERRORS=1, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '/opt/oracle/MUSERGROUP_DATA.csv'
INTO TABLE MUSERGROUP
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$' 
TRAILING NULLCOLS
(
    MUSERGROUPPK  INTEGER EXTERNAL,
    USERGROUPCODE CHAR,
    USERGROUPNAME CHAR,
    USERGROUPDESC CHAR,
    STATUS        CHAR,
    LASTUPDATED   TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
    UPDATEDBY     CHAR
)