OPTIONS (DIRECT=TRUE, ERRORS=0, BINDSIZE=8000000, COLUMNARRAYROWS=10000, READSIZE=8388608)
LOAD DATA
INFILE '../data_export/TSECURITIESITEM_DATA.csv'
INTO TABLE TSECURITIESITEM
FIELDS CSV WITH EMBEDDED TERMINATED BY '#' OPTIONALLY ENCLOSED BY '$'
TRAILING NULLCOLS
(
    TSECURITIESITEMPK   INTEGER EXTERNAL,
    TINCOMINGFK         INTEGER EXTERNAL,
    ITEMNO              CHAR,
    STATUS              CHAR,
    NUMERATOR           INTEGER EXTERNAL
)
